"""Image generation utilities using external APIs like OpenAI DALL-E."""

from __future__ import annotations

import base64
import os
from typing import Optional

import importlib

try:
    import openai
except ModuleNotFoundError:  # pragma: no cover - optional dependency
    openai = None  # type: ignore

from error_logger import log_error
from modules.api_keys import get_api_key
from modules.utils import project_path

MODULE_NAME = "image_generator"

__all__ = ["generate_image", "generate_image_url", "get_info", "get_description"]


def generate_image(
    prompt: str,
    *,
    provider: str = "openai",
    model: str = "dall-e-3",
    size: str = "512x512",
    save_dir: str = "generated_images",
) -> str:
    """Generate an image from ``prompt`` and save it locally.

    Parameters
    ----------
    prompt:
        Text description of the desired image.
    provider:
        API provider identifier. Currently only ``"openai"`` is supported.
    model:
        Model identifier for the provider, e.g. ``"dall-e-3"``.
    size:
        Image resolution string (for providers that support it), e.g. ``"512x512"``.
    save_dir:
        Folder within the project directory to store generated images. If an
        absolute path is provided it will be used as-is.

    Returns
    -------
    str
        Path to the saved image on success, otherwise an error message.
    """
    prov = provider.lower()
    if prov != "openai":
        return f"Provider '{provider}' not supported"

    api_key = get_api_key(prov)
    if not api_key:
        return "Missing API key"

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "prompt": prompt,
        "model": model,
        "n": 1,
        "size": size,
        "response_format": "b64_json",
    }
    try:
        requests = importlib.import_module("requests")
        resp = requests.post(
            "https://api.openai.com/v1/images/generations",
            json=payload,
            headers=headers,
            timeout=60,
        )
        resp.raise_for_status()
        data = resp.json()
        b64 = data.get("data", [{}])[0].get("b64_json")
        if not b64:
            return "No image data returned"
        image_bytes = base64.b64decode(b64)
        if not os.path.isabs(save_dir):
            save_dir = project_path(save_dir)
        os.makedirs(save_dir, exist_ok=True)
        filename = os.path.join(save_dir, f"image_{len(os.listdir(save_dir)) + 1}.png")
        with open(filename, "wb") as f:
            f.write(image_bytes)
        return filename
    except Exception as exc:  # pragma: no cover - network or file failure
        log_error(f"[image_generator] {exc}")
        return f"Error: {exc}"


def generate_image_url(prompt: str, *, size: str = "1024x1024") -> str:
    """Return an image URL generated by DALL-E for ``prompt``.

    Parameters
    ----------
    prompt:
        Text description of the desired image.
    size:
        Image resolution, e.g. ``"1024x1024"``.

    Returns
    -------
    str
        URL string on success, otherwise an error message.
    """
    if openai is None:
        log_error("openai package not available")
        return "OpenAI library not installed"

    try:
        from dotenv import load_dotenv  # pragma: no cover - optional
    except Exception:
        def load_dotenv() -> None:  # pragma: no cover - fallback
            return None
    load_dotenv()

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        log_error("OPENAI_API_KEY not found")
        return "Missing API key"

    try:
        if hasattr(openai, "OpenAI"):
            client = openai.OpenAI(api_key=api_key)
            resp = client.images.generate(prompt=prompt, n=1, size=size)
            url = resp.data[0].url
        else:
            openai.api_key = api_key
            resp = openai.Image.create(prompt=prompt, n=1, size=size)
            url = resp["data"][0]["url"]
        return url
    except openai.OpenAIError as exc:  # pragma: no cover - network failure
        status = getattr(exc, "status_code", getattr(exc, "http_status", "n/a"))
        body = getattr(exc, "response", getattr(exc, "error", str(exc)))
        log_error(f"[image_generator] API error {status}", context=str(body))
        return f"Error {status}: {body}"
    except Exception as exc:  # pragma: no cover - unexpected failure
        log_error(f"[image_generator] {exc}")
        return f"Error: {exc}"


def get_info() -> dict:
    """Return module metadata for discovery."""
    return {
        "name": MODULE_NAME,
        "description": "Generate images from text prompts using DALL-E or similar APIs.",
        "functions": ["generate_image", "generate_image_url"],
    }


def get_description() -> str:
    """Return a short description of this module."""
    return "Utilities to create images from text prompts via external APIs."
